# Project: IPChanger
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = ../Source/Obj/IPChanger_private.res
OBJ  = ../Source/Obj/main.o ../Source/Obj/memory.o ../Source/Obj/window.o ../Source/Obj/config.o ../Source/Obj/version.o ../Source/Obj/tools.o ../Source/Obj/serverlist.o $(RES)
LINKOBJ  = ../Source/Obj/main.o ../Source/Obj/memory.o ../Source/Obj/window.o ../Source/Obj/config.o ../Source/Obj/version.o ../Source/Obj/tools.o ../Source/Obj/serverlist.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows  -s 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = ../IPChanger.exe
CXXFLAGS = $(CXXINCS)   -O3
CFLAGS = $(INCS)   -O3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ../IPChanger.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "..\IPChanger.exe" $(LIBS)

../Source/Obj/main.o: ../Source/main.cpp
	$(CPP) -c ../Source/main.cpp -o ../Source/Obj/main.o $(CXXFLAGS)

../Source/Obj/memory.o: ../Source/memory.cpp
	$(CPP) -c ../Source/memory.cpp -o ../Source/Obj/memory.o $(CXXFLAGS)

../Source/Obj/window.o: ../Source/window.cpp
	$(CPP) -c ../Source/window.cpp -o ../Source/Obj/window.o $(CXXFLAGS)

../Source/Obj/config.o: ../Source/config.cpp
	$(CPP) -c ../Source/config.cpp -o ../Source/Obj/config.o $(CXXFLAGS)

../Source/Obj/version.o: ../Source/version.cpp
	$(CPP) -c ../Source/version.cpp -o ../Source/Obj/version.o $(CXXFLAGS)

../Source/Obj/tools.o: ../Source/tools.cpp
	$(CPP) -c ../Source/tools.cpp -o ../Source/Obj/tools.o $(CXXFLAGS)

../Source/Obj/serverlist.o: ../Source/serverlist.cpp
	$(CPP) -c ../Source/serverlist.cpp -o ../Source/Obj/serverlist.o $(CXXFLAGS)

../Source/Obj/IPChanger_private.res: IPChanger_private.rc 
	$(WINDRES) -i IPChanger_private.rc --input-format=rc -o ../Source/Obj/IPChanger_private.res -O coff 
